CREATE DATABASE IF NOT EXISTS otoparkOtomasyon CHARACTER SET UTF8MB4 COLLATE UTF8MB4_TURKISH_CI;
USE otoparkOtomasyon;

CREATE TABLE IF NOT EXISTS aracKayitBilgi(
plaka VARCHAR(15) NOT NULL PRIMARY KEY,
marka VARCHAR(20) NOT NULL,
model VARCHAR(25) NOT NULL,
renk VARCHAR(20) NOT NULL
) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_TURKISH_CI;


CREATE TABLE IF NOT EXISTS aboneTc(
TC VARCHAR(11) NOT NULL,
plaka VARCHAR(15) NOT NULL,
CONSTRAINT plaka FOREIGN KEY (plaka) REFERENCES otoparkOtomasyon.aracKayitBilgi(plaka),
marka VARCHAR(20) NOT NULL,
model VARCHAR(25) NOT NULL,
renk VARCHAR(20) NOT NULL

) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_TURKISH_CI;

CREATE TABLE IF NOT EXISTS aboneKayitBilgi(
ad VARCHAR(30) NOT NULL,
soyad VARCHAR(35) NOT NULL,
telNo VARCHAR(11) NOT NULL,
adres VARCHAR(200) NOT NULL,
TC VARCHAR(11) NOT NULL
) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_TURKISH_CI;


CREATE TABLE IF NOT EXISTS aracGirisCikis(
aracGiris_id INT  UNIQUE AUTO_INCREMENT,
giris_saati VARCHAR(45) NOT NULL,
cikis_saati VARCHAR(45),
tutar VARCHAR(45),
park_suresi VARCHAR(5),
plaka VARCHAR(15) NOT NULL,
CONSTRAINT plaka FOREIGN KEY (plaka) REFERENCES otoparkOtomasyon.aracKayitBilgi(plaka)
) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_TURKISH_CI;

CREATE TABLE IF NOT EXISTS uyelikTarihBilgi(
uyelik_id INT  UNIQUE AUTO_INCREMENT,
abonelikBaslangicTarih VARCHAR(45) NOT NULL,
abonelikBitisTarih VARCHAR(45),
TC VARCHAR(11) NOT NULL
) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_TURKISH_CI;